language: node_js
sudo: true
branches:
    only:
    - master
node_js:
  - "7"
install:
  - npm install
script:
  - npm test
deploy:
    provider: s3
    access_key_id: "AKIAIO23RSRLNSN6PYLA"
    secret_access_key: "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"
    bucket: deploy-bucket-sem-project-5
    local_dir: dpl_cd_upload
    skip_cleanup: true
    acl: public_read
    region: eu-west-1
    provider: codedeploy
    access_key_id: "AKIAIO23RSRLNSN6PYLA"
    secret_access_key: "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"
    bucket: deploy-bucket-sem-project-5
    revision_type: github
    application: sem-project-5
    deployment_group: sem-project-5-dep-group
    region: eu-west-1
    wait-until-deployed: true